version: '3'

services:

  oqs:
    container_name: oqs.localhost
    build:
      context: ../
      dockerfile: ./build/Dockerfile
      no_cache: true
    tty: true
    ports:
      - 1323:1323
    environment:
      SERVICE_URL: "http://oqs.localhost:1323"