version: '3'

services:

  oqs:
    container_name: oqs.localhost
    image: golang:1.22.1
    tty: true
    ports:
      - 1323:1323
    working_dir: /app/cmd/main
    command:
      - /bin/sh
      - -c 
      - |
        go install github.com/cosmtrek/air@latest
        air
    volumes:
      - ./../:/app
    environment:
      SERVICE_URL: "http://oqs.localhost:1323"